version: "3.9"
services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: "no" 
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mednanny
      MYSQL_USER: testuser
      MYSQL_PASSWORD: root
    expose:
      - "3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro

  adminer: 
    container_name: adminer
    image: adminer:latest
    restart: "no" 
    ports: 
      - 8080:8080
    environment:
      ADMINER_DESIGN: galkaev
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro

