version: "3.9"
services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: "no" 
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mednanny
      MYSQL_USER: testuser
      MYSQL_PASSWORD: root
    expose:
      - "3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro

  tomcat:
    container_name: tomcat
    image: tomcat:latest
    ports:
      - 8080:8080
    volumes:
      - ./WebContent:/usr/local/tomcat/webapps/mednanny/
      - /etc/localtime:/etc/localtime:ro
      - ./conf/context.xml:/usr/local/tomcat/conf/context.xml
      - ./conf/server.xml:/usr/local/tomcat/conf/server.xml 
      - ./conf/mednanny.xml:/usr/local/tomcat/conf/Catalina/localhost/
    depends_on:
      - db
    environment:
      JDBC_URL: jdbc:mysql://db:3306/mednanny?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
      JDBC_USER: testuser
      JDBC_PASS: root 
    expose:
      - "8080"
    restart: "no"
    
  adminer: 
    container_name: adminer
    image: adminer:latest
    restart: "no" 
    ports: 
      - 8081:8080
    environment:
      ADMINER_DESIGN: galkaev
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro

