version: "3.9"
services:
  db:
    container_name: db
    image: mysql:5.7
    restart: "always" 
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mednannypw
      MYSQL_DATABASE: mednanny
      MYSQL_USER: testuser
      MYSQL_PASSWORD: mednannypw
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
      - ./conf/my.cnf:/etc/my.cnf

  tomcat:
    container_name: tomcat
    image: tomcat:9.0.68
    ports:
      - 8080:8080
    volumes:
      - ./WebContent:/usr/local/tomcat/webapps/mednanny/
      - /etc/localtime:/etc/localtime:ro
      - ./conf/context.xml:/usr/local/tomcat/conf/context.xml
      - ./conf/server.xml:/usr/local/tomcat/conf/server.xml 
    depends_on:
      - db
    environment:
      JDBC_URL: jdbc:mysql://db:3306/mednanny?&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=50
      JDBC_ROOTUSER: root
      JDBC_PASS: mednannypw 
    restart: "always"
    
  adminer: 
    container_name: adminer
    image: adminer:latest
    restart: "always" 
    ports: 
      - 8081:8080
    environment:
      ADMINER_DESIGN: galkaev
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro

